/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.santillanr_finalexam;

import javax.swing.*;

/**
 *
 * @author Janine Rachelle
 */
public class SalaryCalculator extends javax.swing.JFrame {
    
    String hw;
    String hr;
    String tp;
    String lp;
    
    double hoursworked;
    double rate;
    int tax;
    double loan;
    
    SantillanR_FinalExam calcu = new SantillanR_FinalExam();
    
    DefaultListModel<String> listmodel = new DefaultListModel<>();
    /**
     * Creates new form SalaryCalculator
     */
    public SalaryCalculator() {
        initComponents();
        listsalary.setModel(listmodel);
        txtlp.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbloan = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listsalary = new javax.swing.JList<>();
        btncompute = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        lblnetpay = new javax.swing.JLabel();
        txthw = new javax.swing.JTextField();
        txthr = new javax.swing.JTextField();
        txttp = new javax.swing.JTextField();
        txtlp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(144, 187, 231));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("SALARY CALCULATOR");

        jLabel2.setText("Hourly Worked:");

        jLabel3.setText("Hourly Rate:");

        jLabel4.setText("Tax Percentage:");

        cbloan.setText("Do you have a loan?");
        cbloan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbloanActionPerformed(evt);
            }
        });

        jLabel5.setText("Loan Payment:");

        listsalary.setBackground(new java.awt.Color(219, 249, 247));
        listsalary.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listsalary);

        btncompute.setBackground(new java.awt.Color(51, 153, 255));
        btncompute.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncompute.setText("Compute");
        btncompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomputeActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(0, 153, 255));
        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        lblnetpay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblnetpay.setText("Net Salary: P 0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btncompute)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnclear))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lblnetpay, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txthw)
                                .addComponent(txthr, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(txttp, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(txtlp)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cbloan)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txthr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(txthw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(cbloan)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncompute)
                    .addComponent(btnclear))
                .addGap(34, 34, 34)
                .addComponent(lblnetpay)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txthw.setText("");
        txthr.setText("");
        txtlp.setText("");
        txttp.setText("");
        listmodel.clear();
        txtlp.setEnabled(false);
        cbloan.setSelected(false);
    }//GEN-LAST:event_btnclearActionPerformed

    private void cbloanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbloanActionPerformed
        // TODO add your handling code here:
        txtlp.setEnabled(cbloan.isSelected());
        txtlp.setText("");
    }//GEN-LAST:event_cbloanActionPerformed

    private void btncomputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomputeActionPerformed
        // TODO add your handling code here:
               listmodel.clear();
        
        hr = txthr.getText();
        hw = txthw.getText();
        lp = txtlp.getText();
        tp = txttp.getText();
        
        double utang = Double.parseDouble(lp);
        double sahod = calcu.compute(hoursworked, rate, tax, loan);
        
        if(utang > sahod){
        JOptionPane.showMessageDialog(this, "Mas malaki pa utang kaysa sa sahod!");
        return;
        }
            
        else if (hr.isEmpty() || hw.isEmpty() || tp.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Lagyan mo lahat!");
            return;
        }
        
        else if(cbloan.isSelected()){
        try{ 
            hoursworked = Double.parseDouble(hw);
            rate = Double.parseDouble(hr);
            tax = Integer.parseInt(tp);
            loan = Double.parseDouble(lp);
            
            listmodel.addElement("Hours Worked: " + String.format("%.2f", hoursworked));
            listmodel.addElement("Hour Rate: " + String.format("%.2f", rate));
            listmodel.addElement("Tax Percentage: " + String.format("%d", tax));
            listmodel.addElement("Loan Payment: " + String.format("%.2f", loan));
            
            lblnetpay.setText("Total Net Pay: P" + String.format("%2.2f", calcu.compute(hoursworked, rate, tax, loan)));
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Number lang ilagay mo!");
        }            
        }
        
        else{
        try{
            hoursworked = Double.parseDouble(hw);
            rate = Double.parseDouble(hr);
            tax = Integer.parseInt(tp);
            
            listmodel.addElement("Hours Worked: " + String.format("%.2f", hoursworked));
            listmodel.addElement("Hour Rate: " + String.format("%.2f", rate));
            listmodel.addElement("Tax Percentage: " + String.format("%d", tax));
            
            lblnetpay.setText("Total Net Pay: P" + String.format("%2.2f", calcu.compute(hoursworked, rate, tax)));
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Number lang ilagay mo!");
        }
        
        }
    }//GEN-LAST:event_btncomputeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }   catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex){
                java.util.logging.Logger.getLogger(SalaryCalculator.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                new SalaryCalculator().setVisible(true);
            }
        });
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SalaryCalculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btncompute;
    private javax.swing.JCheckBox cbloan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblnetpay;
    private javax.swing.JList<String> listsalary;
    private javax.swing.JTextField txthr;
    private javax.swing.JTextField txthw;
    private javax.swing.JTextField txtlp;
    private javax.swing.JTextField txttp;
    // End of variables declaration//GEN-END:variables
}
